export const products = [
  {
    id: "1",
    name: "product 1",
    price: "€ 19,99",
    rating: "9.1/10",
    description: "This is product 1.",
    brand: "Triangle",
  },
  {
    id: "2",
    name: "product 2",
    price: "€ 39,99",
    rating: "4.0/10",
    description: "This is product 2.",
    brand: "Rectangle",
  },
  {
    id: "3",
    name: "product 3",
    price: "€ 4,99",
    rating: "10/10",
    description: "This is product 3.",
    brand: "Bol",
  },
  {
    id: "4",
    name: "product 4",
    price: "€ 24,49",
    rating: "7.2/10",
    description: "This is product 4.",
    brand: "Octagon",
  },
  {
    id: "5",
    name: "product 5",
    price: "€ 9,99",
    rating: "8.9/10",
    description: "This is product 5.",
    brand: "Quadrant",
  },
  {
    id: "6",
    name: "product 6",
    price: "€ 99,99",
    rating: "8.0/10",
    description: "This is product 6.",
    brand: "Heptagon",
  },
  {
    id: "7",
    name: "product 7",
    price: "€ 114,99",
    rating: "6.3/10",
    description: "This is product 7.",
    brand: "Tentagon",
  },
];
